### PR TITLE
Create a new scripted shellmap

### PR DESCRIPTION
**Pull request by Phrohdoh**
This depends on [OpenRA/11819](https://github.com/OpenRA/OpenRA/pull/11819).
screen shot 2016-08-13 at 7 04 12 pm
screen shot 2016-08-13 at 7 04 19 pm

### CODE REVIEW

**Comment by evgeniysergeev** [comment]
Shellmap modifies palette?It darker than should be, after shellmap loadscreen also looks darker

**Comment by Phrohdoh** [comment]
@evgeniysergeev This _will_ crash because the referenced PR has not been merged.
Yes, it modifies the overall palette via the GlobalLightingPalette world trait.

**Comment by evgeniysergeev** [comment]
this is not acceptable. we trying to make it look like dune2. we should not modify palette

**Comment by Micr0Bit** [comment]
beside the missing PR and the modified palette ... the shellmap itself doesnt look good ... where are the slabs ? why is every building with 2-3 cells of space to each other

we can do that better ... dont need to add a filler , sry but 

:-1:

**Pull request merged**
