### PR TITLE
Checked health and corrected wrong values not matching the original

### PR DESCRIPTION
**Pull request by Micr0Bit**
Part of #17

### CODE REVIEW

**Comment by abcdefg30** [comment]
Rebased the PR, so this should be good to go.

**Comment by Micr0Bit** [comment]
thx @abcdefg30

**Comment by Micr0Bit** [comment]
@Nyerguds : some of the hitpoints in the dune-insider (page 16,17,18,19) seem to differ from the rules-1.00.ini/rules-1.07.ini ... the outpost for example is written down with 1000 hp ... but has only 500 in 1.00/1.07

**Comment by Nyerguds** [comment]
@Micr0Bit Well, y'know, it's not I _wrote_ any of those things; those ini values are dumped straight from the original exe files :P

**Comment by Micr0Bit** [comment]
nevermind , i just thought you know more about that

**Comment by Nyerguds** [comment]
No, I'm the guy with internal knowledge about C&C1. For Dune II, TrueBrain or one of the people of the OpenDune project, or MrFlibble, would be the ones to ask.

**Pull request merged**
