### PR TITLE
Fixed the content detection

### PR DESCRIPTION
**Pull request by Mailaender**
The dependency on Dune 2000 is really odd though.

### CODE REVIEW

**Comment by fleeingmoth** [comment]
IBM.PAL fix works

**Comment by evgeniysergeev** [comment]
> IBM.PAL fix works

Hello @fleeingmoth , did you test with latest d2 (updated to OpenRA engine release-20210321). This pull request can be outdated, because of updates in main branch. I'll take a look and merge it.

**Comment by fleeingmoth** [comment]
@evgeniysergeev I did some troubleshooting on the OpenRA discord with penev92, and we figured out that the instructions for where to put the .PAK files was outdated- for Windows, they should go in `Users\Username\AppData\Roaming\OpenRA\Content\d2' and not `Documents\OpenRA\Content\d2`. This is due to an OpenRA update I think.

**Comment by evgeniysergeev** [comment]
@penev92 , @Mailaender 
Do I understand correctly, that after this commit: https://github.com/OpenRA/d2/commit/a74075a8731c71341e33d14ae2eb7a8b77280f7e
This PR can be closed. because changes already applied?

**Comment by Mailaender** [comment]
I have no idea, but I am not rebasing this after getting ignored for 2 years.

**Pull request closed without merging**
