### PR TITLE
Make starting BaseActor: ConYard instead of MCV

### PR DESCRIPTION
**Pull request by MustaphaTR**

### CODE REVIEW

**Comment by Micr0Bit** [comment]
I'll test this on the weekend

**Comment by TheRaffy** [comment]
What happens when startpositions of a map are located on the sand? Or on the boarder between sand and rocks?, or when a mountain is blocking the building? 

I would not recommend to establish unwritten mapping dogmatic rules, like "starting positions have to be always on rocks" and if not, it will be unplayable or might even crash. your fault.
That's a buggy concept. 

I guess an automatic deploy function for mcv's,that will block deploying, if there's something in the way, would be a better sollution. The AI should already have such kind of function.

wonderfull would be a checkbox depolyed [x].  :)

**Comment by abcdefg30** [comment]
D2k already starts with deployed construction yards as well. If spawnpoints are put on the sand, that's a bug in the map I'd say. Such maps could also edit the rules for starting units and let the mcv spawn (undeployed).

**Comment by TheRaffy** [comment]
because its done in d2k doesn't mean it's a cleaner sollution^^  
My suggestion would make such custom rules redundant.

**Comment by Micr0Bit** [comment]
this is how you start in dune 2
bildschirmfoto 2017-07-21 um 12 40 31

and this is how you start in d2000
bildschirmfoto 2017-07-21 um 12 40 17

**Comment by TheRaffy** [comment]
Dude, hornestly? I even played dune1. 
The question is shall it be mapper friendly and bugless or not? 
What I'm saying is that you can't assume, that every potential mapper knows that starting points should be on rocks.

**Comment by Micr0Bit** [comment]
if you want this to be mapper-friendly, you could open a ticket and ask for a feature that (for example) denies any spawnpoints on desert or on the boarder between sand and rocks or near a mountain. "If its a ConstructionYard" and not a "Mcv" 

https://github.com/OpenRA/OpenRA/issues

**Comment by Phrohdoh** [comment]
@TheRaffy You can guide mappers in the right direction though.

Perhaps rules need to be written that limit where certain, map-editor only, actors can be placed.
If you cannot place the currently selected actor and the mouse's position display a graphic indicating an error (red X, red cross-hatching, etc).

**Comment by Phrohdoh** [comment]
> if you want this to be mapper-friendly, you could open a ticket and ask for a d2k/d2 feature that (for example) denies placing a spawnpoint when the area doesnt fit a construction-yard

I just realized that @Micr0Bit has already suggested a fix for this.
I need to read a bit better before responding.

**Comment by evgeniysergeev** [comment]
Hello @MustaphaTR, can you update pr to current d2 master branch?

**Comment by MustaphaTR** [comment]
Rebased.

**Comment by MustaphaTR** [comment]
Updated again.

**Pull request merged**
